export enum SupportCategory {
  DRIVER_REPORT = 'DRIVER_REPORT',
  PASSENGER_REPORT = 'PASSENGER_REPORT',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  APP_BUG = 'APP_BUG',
  ROUTE_ISSUE = 'ROUTE_ISSUE',
  GENERAL = 'GENERAL',
}
