export const APP_CONSTANTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
  BCRYPT_SALT_ROUNDS: 12,
  JWT_EXPIRATION: '1h',
  REFRESH_TOKEN_EXPIRATION: '7d',
  API_PREFIX: 'api/v1',
} as const;
